version: '3.8'

services:
    gateway:
        build: ./gateway
        restart: always
        volumes:
          - ./gateway:/var/www/gateway
        env_file:
            - .env
        ports:
            - ${API_GATEWAY_PORT}:${API_GATEWAY_PORT}
        networks:
            - backend
        depends_on:
            - media
            - live
            - token
            - user

    media:
        build: ./media
        restart: always
        volumes:
          - ./media:/var/www/media
        env_file:
            - .env
        ports:
            - ${MEDIA_SERVICE_PORT}:${MEDIA_SERVICE_PORT}
        networks:
            - backend

    live:
        build: ./live
        restart: always
        volumes:
          - ./live:/var/www/live
        env_file:
            - .env
        ports:
            - ${LIVE_SERVICE_PORT}:${LIVE_SERVICE_PORT}
        networks:
            - backend

    token:
        build: ./token
        restart: always
        volumes:
          - ./token:/var/www/token
        env_file:
            - .env
        ports:
            - ${TOKEN_SERVICE_PORT}:${TOKEN_SERVICE_PORT}
        networks:
            - backend

    user:
        build: ./user
        restart: always
        volumes:
          - ./user:/var/www/user
        env_file:
            - .env
        ports:
            - ${USER_SERVICE_PORT}:${USER_SERVICE_PORT}
        networks:
            - backend

    front:
        build: ./front
        restart: always
        volumes:
        - ./front:/var/www/front
        - /var/www/front/node_modules
        env_file:
        - .env
        ports:
        - ${FRONT_SERVICE_PORT}:${FRONT_SERVICE_PORT}
        networks:
        - frontend

networks:
    backend:
        driver: bridge
    frontend:
        external: true
        name: infrastructure

volumes:
    gateway: 
    media:
    live:
    token:
