version: '3.8'

services:
    gateway:
        build: ./gateway
        restart: always
        volumes:
          - ./gateway:/var/www/gateway
        env_file:
            - .env
        ports:
            - ${API_GATEWAY_PORT}:${API_GATEWAY_PORT}
        networks:
            - backend
        depends_on:
            - media
            - live
            - token
            - mailer
            - user

    media:
        build: ./media
        restart: always
        volumes:
          - ./media:/var/www/media
        env_file:
            - .env
        ports:
            - ${MEDIA_SERVICE_PORT}:${MEDIA_SERVICE_PORT}
        networks:
            - backend

    live:
        build: ./live
        restart: always
        volumes:
          - ./live:/var/www/live
        env_file:
            - .env
        ports:
            - ${LIVE_SERVICE_PORT}:${LIVE_SERVICE_PORT}
        networks:
            - backend

    token:
        build: ./token
        restart: always
        volumes:
          - ./token:/var/www/token
        env_file:
            - .env
        ports:
            - ${TOKEN_SERVICE_PORT}:${TOKEN_SERVICE_PORT}
        networks:
            - backend

    mailer:
        build: ./mailer
        restart: always
        volumes:
          - ./mailer:/var/www/mailer
        env_file:
            - .env
        ports:
            - ${MAILER_SERVICE_PORT}:${MAILER_SERVICE_PORT}
        networks:
            - backend

    user:
        build: ./user
        restart: always
        volumes:
          - ./user:/var/www/user
        env_file:
            - .env
        ports:
            - ${USER_SERVICE_PORT}:${USER_SERVICE_PORT}
        networks:
            - backend

    db:
        image: 'mongo:3.7'
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
            MONGO_USER: ${MONGO_USER}
            MONGO_PASSWORD: ${MONGO_PASSWORD}
        volumes:
            - "./db/data/db-files:/data/db"
            - "./db/init/:/docker-entrypoint-initdb.d/"
        ports:
            - 27017:27017
        networks:
            - backend

networks:
    backend:
        driver: bridge

volumes:
    gateway: 
    media:
    live:
    token:
    mailer: