version: '3.8'

services:
    gateway:
        build:
            dockerfile: Dockerfile
            context: ./gateway
            target: production
        restart: always
        volumes:
          - ./gateway:/var/www/gateway
        env_file:
            - .env
        ports:
            - ${API_GATEWAY_PORT}:${API_GATEWAY_PORT}
        networks:
            - backend
        depends_on:
            - media
            - live
            - token
            - user
            - redis

    media:
        build:
            dockerfile: Dockerfile
            context: ./media
            target: production
        restart: always
        volumes:
          - ./media:/var/www/media
        env_file:
            - .env
        ports:
            - ${MEDIA_SERVICE_PORT}:${MEDIA_SERVICE_PORT}
        networks:
            - backend

    live:
        build:
            dockerfile: Dockerfile
            context: ./live
            target: production
        restart: always
        volumes:
          - ./live:/var/www/live
        env_file:
            - .env
        ports:
            - ${LIVE_SERVICE_PORT}:${LIVE_SERVICE_PORT}
        networks:
            - backend

    token:
        build:
            dockerfile: Dockerfile
            context: ./token
            target: production
        restart: always
        volumes:
          - ./token:/var/www/token
        env_file:
            - .env
        ports:
            - ${TOKEN_SERVICE_PORT}:${TOKEN_SERVICE_PORT}
        networks:
            - backend

    user:
        build:
            dockerfile: Dockerfile
            context: ./user
            target: production
        restart: always
        volumes:
          - ./user:/var/www/user
        env_file:
            - .env
        ports:
            - ${USER_SERVICE_PORT}:${USER_SERVICE_PORT}
        networks:
            - backend

    front:
        build:
            dockerfile: Dockerfile
            context: ./front
            target: production
        restart: always
        volumes:
            - ./front:/var/www/front
            - /var/www/front/node_modules
        env_file:
            - .env
        ports:
            - ${FRONT_SERVICE_PORT}:${FRONT_SERVICE_PORT}
        networks:
            - frontend

    redis:
        image: redis:alpine
        restart: always
        volumes:
            - redis:/data
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}
        networks:
            - backend

networks:
    backend:
        driver: bridge