name: Deplot to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup SSH key and certificate
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/github-actions.pem
          chmod 600 ~/.ssh/github-actions.pem

      - name: Create .env
        run: |
          echo "${{ secrets.ENV }}" > .env

      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          TARGET: "/home/ubuntu"
          EXCLUDE: "/dist/, /node_modules/, /front/"
          SCRIPT_BEFORE: |
            cd /home/ubuntu
            pm2 stop all
          SCRIPT_AFTER: |
            cd /home/ubuntu
            mkdir -p ~/gateway/secrets/
            echo "${{ secrets.PUBLIC_CERTIFICATE }}" > ~/gateway/secrets/public-certificate.pem
            echo "${{ secrets.PRIVATE_KEY }}" > ~/gateway/secrets/private-key.pem
            chmod 666 ~/gateway/secrets/public-certificate.pem
            chmod 666 ~/gateway/secrets/private-key.pem
            pm2 start all
          



        
            



        