name: Deplot to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/github-actions.pem
          chmod 600 ~/.ssh/github-actions.pem
          cat ~/.ssh/github-actions.pem
          cat ~/.ssh/know_hosts
      
      - name: Test SSH
        run: |
          touch ~/text.txt
          echo "Hello World" > ~/text.txt
          scp -i ~/.ssh/github-actions.pem ~/text.txt ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/text.txt


        
            



        